### ISSUE TITLE
conda package and source install conflict

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/Tax-Calculator#296]
@talumbau, this is mostly a question for you. 

Conda installing the taxcalc package locally causes errors for a contributor who wants to interact with the taxcalc source code. Since many of our contributors will be new to conda, this might trip them up if they ever 'accidentally' execute `conda install taxcalc`, even just to play around. This raises a couple of questions:

1. Is there a way to keep the two from conflicting when they are in the same environment? 

2. If the answer to the first question is  "no," then it seems we need to decide whether it should be users or contributors who need to create and activate a new conda environment. 

Am I thinking about this the right way? 

cc @martinholmer

**Comment by talumbau** [comment]
Ah, maybe I should start sort of one step 'higher'. I thought there would be a class of users where they could do productive things with just the following: a JSON file of the parameters that they wanted to tweak, a PUF (or equivalent) dataset, and some basic Python skills. For this use case, a conda package is a great way to go. You don't have to mess with the "guts", you can just make changes to your "Plan Y",  run the calculator as shown in the notebooks, and then you are good to go.

If you are interacting with the source, this is more what I would consider 'development'. In that case, you don't want the conda package installed because you are probably in some kind of iteration of "make changes to source, see how they impact 'the answer', make more changes to source, etc." In this case, I typically set up some kind of 'run script' with a terminal or IPython notebook at the top of the repo. Then, when I make changes, I will do something like `python check.py` from the top of the repo. In that script, the `import taxcalc` will import the package found in the `taxcalc/` directory which has my latest changes.

So, the overall answer is that development work should be done in an environment where the package is not installed. If one wants to uninstall a package, you can just do `conda remove taxcalc`.

The developer case would still want a conda environment because, presumably, you would want to run the tests (and likely add tests) and also have the proper version of pandas, numpy, numba, etc. That's actually my fault for not creating an `environment.yaml` file. I'll be adding one soon. That way collaborators who want to develop the package could do something like:

```
git clone git@github.com:OpenSourcePolicyCenter/Tax-Calculator
cd Tax-Calculator
conda env create
py.test
```

The `conda env create` would install everything needed to make the package run, but it wouldn't install the package itself.

**Comment by MattHJensen** [comment]
> Ah, maybe I should start sort of one step 'higher'. I thought there would be a class of users where they could do productive things with just the following: a JSON file of the parameters that they wanted to tweak, a PUF (or equivalent) dataset, and some basic Python skills. For this use case, a conda package is a great way to go. You don't have to mess with the "guts", you can just make changes to your "Plan Y", run the calculator as shown in the notebooks, and then you are good to go.

Yep, we are on the same page here! I'm thinking we turn our focus to this type of user in the near future, once everything has settled down with our "contributor docs". 

Just to rehash and make sure we are all on the same page, the concern is that our collaborators, many of whom will also be users, will be tripped up by the distinction between "user" and "developer"; they will very often be new to conda and github and many other things after all. In other words, they will think "oh, I want to contribute to the project, so I'll follow the contributor guide." So they'll go get the source from github. Then they'll see the user guide and say, "oh, I'm a user, so I should probably do this `conda install -c ospc taxcalc` thing." 

I think the `enviornment.yaml` will solve this problem, but let me clarify:

Rather than doing:

> conda env create
py.test

Developers would actually do:

    conda env create
    source activate tax
    py.test

And then they could `conda install -c ospc taxcalc` in their main anaconda environment without messing up their `tax` environment. I checked out #297 locally this morning, and everything seems to work this way. 

If all of this is true, then I'd advocate the default environment name created with `environment.yaml` to be something like `taxcalc-dev` rather than `tax`. 

##### Followup Questions

1. Let's say everything above works as described, some users might still accidentally install the taxcalc package in their development enviornment. Is there a good way to identify that as the problem and notify the user when they try to run py.test and some tests fail?
2. It doesn't seem like py.test runs properly if you only have the installed taxcalc package. Is that expected? If so, should we have a separate test suite for users, or is it typical to just expect things will work for package users based on our testing during the development process?

**Comment by MattHJensen** [comment]
Ahh, @talumbau, I see that your edits to the contributor guide in #297  confirm this:

>Developers would actually do:
conda env create
source activate tax
py.test

**Comment by talumbau** [comment]
in order:

1. I think there might be some way to say "these tests are failing with package `taxcalc` installed at path blah blah". If we could do that, then the user would see that he has the installed package and not the current source code he is working with. Do you want me to create an issue about this?

2. If you run the tests on current master when using the installed package, you will likely get failures. That is a good thing, because presumably the current master has more features than the installed package. Each new feature should have new tests, so unless you check out the code at our latest tagged release (currently 0.4.9) you will get these errors. I would consider something like the 10 minutes to taxcalc a nice "test" for users. What do you think?

**Comment by MattHJensen** [comment]
Just opened #313 for 1. On 2, I agree that 10_min notebook is a nice way for conda-install users to test that things are working -- this will be even better with the enhancement that Martin is working on that will allow for taxsim formatted data. Closing this issue.
