### ISSUE TITLE
How to pass a temporary file name to a method in pytest?

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/Tax-Calculator#380]
@talumbau and @PeterDSteinberg,
I need a mini tutorial on how to setup a temporary file in the new taxcalc/tests/test_simpletaxio.py file.  The existing tests all seem to "yield" the tempfile __contents__, but what I need  to do is "yield" the tempfile __name__ and pass that name to the method being tested, which will then open and read the tempfile with that name).  How do I do that?

**Comment by talumbau** [comment]
Is it OK to pass in the fixture, and then get the name of the tempfile via the `name` attribute? For example, in this code snippet:

```
def test_csv_to_ascii(csvfile, asciifile):
    output_test = tempfile.NamedTemporaryFile(mode="a", delete=False)
    ascii_output(csv_results=csvfile.name, ascii_results=output_test.name)

```
the csvfile fixture is given to the test, and the filename for the temporary file is passed to the `ascii_output` function. Does that meet the need?


(postscript: I just looked at that test closely for the first time. For some reason, it is using NamedTemporaryFile in the test body, which is not good. The reason is that if the test fails or raises an exception before getting to the `os.remove`, it will pollute the file system. That is the purpose behind using pytest fixtures, and in particular the yield fixtures. So that test should be refactored, but that's a side issue not directly related to your question)

**Comment by martinholmer** [comment]
@talumbau,  Thanks for the help.  I have written a single-test version of test_simpletaxio.py that passes on my computer, but fails when I push the code to Git Hub.  The travis error trace is inscrutable, so I'm hoping you can look at it and tell me what I'm doing wrong.  All this is in Tax-Calculator pull request #376,
which incorporates the latest version of the master branch.   cc @MattHJensen

**Comment by martinholmer** [comment]
@talumbau,  I've worked around the travis-CI problem I mentioned above.  Thanks again.
