### ISSUE TITLE
Calculator, Parameters, and PUF should all support dict-like access

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/Tax-Calculator#99]
Many users might be most comfortable reading/writing variables like this:

```
puf['e00100'] += 1000
```

This is rarely used in the "guts" of the package, but would be expected by user familiar with pandas.

**Comment by feenberg** [comment]
On Mon, 26 Jan 2015, T.J. Alumbaugh wrote:

> 
> Many users might be most comfortable reading/writing variables like this:
> 
> puf['e00100'] += 1000

First, note that changing e00100 shouldn't affect any result, since e00100 
isn't used in our calculation. If the user wants to calculate a marginal 
rate, they could increment e00200, which is part of c00100 and will affect 
tax owed.

More importantly, won't this interfere with compilation? I thought the 
idea was to write code that acted on variables one taxpayer at a time, and 
achieve speed though compilation. Won't it be quite complicated to mix 
vector and scalar instructions for the same variables?

SAS also has an increment operator. I didn't use it becase Stata does not, 
and I was thinking it might complicate mechanical translation. In the end 
it wouldn't have made any difference.

dan
617-863-0343

**Comment by talumbau** [comment]
This was just an example line of code from working with the dropq algorithm. I wouldn't expect this kind of code to appear in the lower level functions. Perhaps the situation I'm considering is even less common than I would think. I'll send you a snippet of the droq algorithm to show why I think it may be useful.

**Comment by feenberg** [comment]
On Tue, 27 Jan 2015, T.J. Alumbaugh wrote:

> 
> This was just an example line of code from working with the dropq algorithm.
> I wouldn't expect this kind of code to appear in the lower level functions.
> Perhaps the situation I'm considering is even less common than I would
> think. I'll send you a snippet of the droq algorithm to show why I think it
> may be useful.

OK, dropq might even benefit from the dictionary approach.

dan

**Comment by talumbau** [comment]
this has all been resolved.
